const I18N = {
  it: { timeline_events:'Eventi timeline', issue_streams:'Temi', hearings_tracked:'Udienze', verified_share:'Quota verificata', density:'Densità eventi per mese', filter:'Filtra per verifica', all:'Tutti', verified:'Verificati', pending:'In attesa', partial:'Parziali', disputed:'Contestati', unverified:'Non verificati', caveat:'Caveat.', issue_clusters:'Cluster temi:', status:'Stato:', use_lim:"Limiti d'uso:", open_source:'Apri fonte', missing_data:'Dati non disponibili in questo export pubblico: ', date_unavailable:'Data non disponibile', network_nodes:'Nodi', network_edges:'Relazioni' },
  en: { timeline_events:'Timeline events', issue_streams:'Issue streams', hearings_tracked:'Hearings tracked', verified_share:'Verified share', density:'Event density by month', filter:'Filter by verification', all:'All', verified:'Verified', pending:'Pending', partial:'Partial', disputed:'Disputed', unverified:'Unverified', caveat:'Caveat.', issue_clusters:'Issue clusters:', status:'Status:', use_lim:'Use limitation:', open_source:'Open source', missing_data:'Data not available in this public export: ', date_unavailable:'Date unavailable', network_nodes:'Nodes', network_edges:'Relations' }
};
let LANG = 'it';
const t = (k) => I18N[LANG][k] || k;

async function loadJson(path) { const response = await fetch(path); if (!response.ok) throw new Error(`Failed to load ${path}`); return response.json(); }
async function safeLoadJson(path, fallback) { try { return await loadJson(path); } catch { return fallback; } }
const slugifyStatus = (text='') => String(text).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const createBadge = (text) => `<span class="badge status-${slugifyStatus(text)}">${text}</span>`;
function formatDateLabel(rawDate){ if(!rawDate) return t('date_unavailable'); const d=new Date(`${rawDate}T00:00:00Z`); return Number.isNaN(d.getTime())?rawDate:new Intl.DateTimeFormat(LANG,{month:'short',day:'2-digit',year:'numeric',timeZone:'UTC'}).format(d); }
const metricCard = (label,value,percent=0)=>`<article class="metric-card"><p class="metric-label">${label}</p><p class="metric-value">${value}</p><div class="metric-bar" style="--metric-width:${percent}%"></div></article>`;
const computeStatusShare=(c,k='verification_status')=>!c.length?0:Math.round((c.filter(i=>slugifyStatus(i[k])==='verified').length/c.length)*100);

function renderMetrics(s){ document.getElementById('metrics-grid').innerHTML=[metricCard(t('timeline_events'),s.timelineCount,100),metricCard(t('issue_streams'),s.issueCount,100),metricCard(t('hearings_tracked'),s.hearingCount,100),metricCard(t('verified_share'),`${s.verifiedShare}%`,s.verifiedShare)].join(''); }
function renderTimelineDensity(items){ const c=document.getElementById('timeline-density'); const b=new Array(12).fill(0); items.forEach(i=>{const d=new Date(`${i.date}T00:00:00Z`); if(!Number.isNaN(d.getTime())) b[d.getUTCMonth()]++;}); const m=Math.max(...b,1); c.innerHTML=`<p class="density-title">${t('density')}</p><div class="density-bars">${b.map(v=>`<span class="density-bar" style="height:${Math.max(12,Math.round((v/m)*100))}%"></span>`).join('')}</div>`; }
function applyStatusFilter(filter='all'){ document.querySelectorAll('.timeline-item, .card, .network-card').forEach(card=>{const badge=card.querySelector('.badge'); if(!badge) return; card.style.display=(filter==='all'||badge.classList.contains(`status-${filter}`))?'':'none';}); document.querySelectorAll('.filter-chip').forEach(btn=>btn.classList.toggle('active',btn.dataset.filter===filter)); }
function renderStatusFilters(){ const p=document.querySelector('.hero-panel'); const w=document.createElement('div'); w.className='status-filters'; w.innerHTML=`<p class="panel-label">${t('filter')}</p><div class="filter-row"><button class="filter-chip active" data-filter="all">${t('all')}</button><button class="filter-chip" data-filter="verified">${t('verified')}</button><button class="filter-chip" data-filter="pending-verification">${t('pending')}</button><button class="filter-chip" data-filter="partially-verified">${t('partial')}</button><button class="filter-chip" data-filter="disputed">${t('disputed')}</button><button class="filter-chip" data-filter="unverified">${t('unverified')}</button></div>`; p.querySelector('.status-filters')?.remove(); p.appendChild(w); w.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>applyStatusFilter(b.dataset.filter)); }
function applyStaticTranslations(){ document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n; if(I18N[LANG][k]) el.textContent=I18N[LANG][k];}); }

async function renderTimeline(data){ const sorted=[...data.items].sort((a,b)=>String(a.date).localeCompare(String(b.date))); document.getElementById('timeline-list').innerHTML=sorted.map(i=>`<article class="timeline-item"><p class="eyebrow">${formatDateLabel(i.date)}</p><h3>${i.title}</h3><p>${i.summary}</p>${createBadge(i.verification_status)}<p><strong>${t('caveat')}</strong> ${i.public_caveat}</p></article>`).join(''); }
async function renderHearings(data){ document.getElementById('hearings-grid').innerHTML=data.hearings.map(i=>`<article class="card"><p class="eyebrow">${formatDateLabel(i.date)}</p><h3>${i.public_title}</h3><p>${i.summary}</p><p><strong>${t('issue_clusters')}</strong> ${i.issue_clusters.join(', ')}</p>${createBadge(i.verification_status)}<p><strong>${t('caveat')}</strong> ${i.public_caveat}</p></article>`).join(''); }
async function renderIssues(data){ document.getElementById('issues-grid').innerHTML=data.issues.map(i=>`<article class="card"><h3>${i.public_label}</h3><p>${i.summary}</p><p><strong>${t('status')}</strong> ${i.current_status}</p>${createBadge(i.verification_status)}<p><strong>${t('caveat')}</strong> ${i.public_caveat}</p></article>`).join(''); }
async function renderSources(data){ document.getElementById('sources-list').innerHTML=data.sources.map(i=>`<article class="source-card"><h3>${i.outlet}</h3><p><strong>${i.title}</strong></p><p>${i.public_value}</p><p><strong>${t('use_lim')}</strong> ${i.use_limitations}</p><p><a href="${i.url}" target="_blank" rel="noopener noreferrer">${t('open_source')}</a></p></article>`).join(''); }
function renderNetwork(data){ const caveat=document.getElementById('network-caveat'); const grid=document.getElementById('network-grid'); if(!grid) return; const nodes=data.nodes||[]; const edges=data.edges||[]; if(caveat) caveat.textContent=data.caveat||''; const nodeCards=nodes.map(n=>`<article class="network-card"><p class="eyebrow">${t('network_nodes')} · ${n.type}</p><h3>${n.public_label}</h3><p>${n.note||''}</p>${createBadge(n.quality_status||'pending verification')}</article>`).join(''); const edgeCards=edges.map(e=>{const source=nodes.find(n=>n.id===e.source)?.public_label||e.source; const target=nodes.find(n=>n.id===e.target)?.public_label||e.target; return `<article class="network-card"><p class="eyebrow">${t('network_edges')}</p><h3>${source} → ${target}</h3><p>${e.public_label}</p>${createBadge(e.quality_status||'pending verification')}</article>`;}).join(''); grid.innerHTML=nodeCards+edgeCards; }

async function init(){ applyStaticTranslations(); const [timeline,hearings,issues,sources,network]=await Promise.all([safeLoadJson('data/exports/public/public_timeline.json',{items:[]}),safeLoadJson('data/exports/public/public_hearings.json',{hearings:[]}),safeLoadJson('data/exports/public/public_issues.json',{issues:[]}),safeLoadJson('data/exports/public/public_sources.json',{sources:[]}),safeLoadJson('data/exports/public/public_network.json',{nodes:[],edges:[],caveat:''})]); await renderTimeline(timeline); renderTimelineDensity(timeline.items); await renderHearings(hearings); await renderIssues(issues); await renderSources(sources); renderNetwork(network); const miss=[]; if(!hearings.hearings.length) miss.push('hearings'); if(!issues.issues.length) miss.push('issues'); if(!sources.sources.length) miss.push('sources'); if(!network.nodes.length) miss.push('network'); if(miss.length){const c=document.querySelector('.caveat-box'); if(c) c.innerHTML+=` <em>${t('missing_data')}${miss.join(', ')}.</em>`;} const verifiedShare=computeStatusShare([...timeline.items,...hearings.hearings,...issues.issues]); renderMetrics({timelineCount:timeline.items.length,issueCount:issues.issues.length,hearingCount:hearings.hearings.length,verifiedShare}); renderStatusFilters(); applyStatusFilter('all'); }

document.getElementById('lang-toggle')?.addEventListener('click',()=>{ LANG=LANG==='it'?'en':'it'; document.getElementById('lang-toggle').textContent=LANG==='it'?'EN':'IT'; init(); });
init();
