const I18N = {
  it: { timeline_events:'Eventi timeline', issue_streams:'Temi', hearings_tracked:'Udienze', verified_share:'Quota verificata', density:'Densità eventi per mese', filter:'Filtra per verifica', all:'Tutti', verified:'Verificati', pending:'In attesa', partial:'Parziali', disputed:'Contestati', unverified:'Non verificati', caveat:'Caveat.', issue_clusters:'Cluster temi:', status:'Stato:', use_lim:"Limiti d'uso:", open_source:'Apri fonte', missing_data:'Dati non disponibili in questo export pubblico: ', date_unavailable:'Data non disponibile', network_nodes:'Nodi', network_edges:'Relazioni', select_node:'Seleziona un nodo o una relazione', related_sources:'Fonti correlate:', error_loading:'Errore nel caricamento di', no_items:'Nessun elemento disponibile', data_timeline:'timeline', data_hearings:'udienze', data_issues:'temi', data_sources:'fonti', data_network:'rete', status_verified:'Verificato', status_partially_verified:'Parzialmente verificato', status_pending_verification:'Verifica in corso', status_disputed:'Contestato', status_unverified:'Non verificato', anti_overclaiming:'Questa visualizzazione non attribuisce responsabilità penali.', network_filters:'Filtri network', only_edges:'Solo relazioni', evidence_panel:'Evidenze', evidence_score:'Rilevanza', data_evidence:'evidenze' },
  en: { timeline_events:'Timeline events', issue_streams:'Issue streams', hearings_tracked:'Hearings tracked', verified_share:'Verified share', density:'Event density by month', filter:'Filter by verification', all:'All', verified:'Verified', pending:'Pending', partial:'Partial', disputed:'Disputed', unverified:'Unverified', caveat:'Caveat.', issue_clusters:'Issue clusters:', status:'Status:', use_lim:'Use limitation:', open_source:'Open source', missing_data:'Data not available in this public export: ', date_unavailable:'Date unavailable', network_nodes:'Nodes', network_edges:'Relations', select_node:'Select a node or relation', related_sources:'Related sources:', error_loading:'Failed to load', no_items:'No items available', data_timeline:'timeline', data_hearings:'hearings', data_issues:'issues', data_sources:'sources', data_network:'network', status_verified:'Verified', status_partially_verified:'Partially verified', status_pending_verification:'Pending verification', status_disputed:'Disputed', status_unverified:'Unverified', anti_overclaiming:'This visualization does not attribute criminal responsibility.', network_filters:'Network filters', only_edges:'Edges only', evidence_panel:'Evidence', evidence_score:'Relevance', data_evidence:'evidence' }
};
let LANG = 'it';
let HYDRA_NETWORK_INSTANCE = null;
let HYDRA_REPLAY_TIMER = null;
const t = (k) => I18N[LANG][k] || k;
const CONTENT_IT = {'First ordinary-trial hearing':'Prima udienza del processo ordinario','Preliminary procedural issues hearing':'Udienza sulle questioni preliminari','Public reporting converges on the opening of the ordinary-trial branch involving approximately 45 defendants, with collaborator-related procedural developments also emerging during the hearing phase.':'Le fonti pubbliche convergono sull\'avvio del ramo di processo ordinario con circa 45 imputati, con ulteriori sviluppi procedurali emersi in udienza.','The hearing focused on preliminary procedural issues, including civil-party participation, territorial-competence objections and defence-rights questions.':'L\'udienza si è concentrata su questioni preliminari, incluse parti civili, eccezioni di competenza territoriale e profili legati al diritto di difesa.','sub judice':'sub iudice','discusso in aula':'discusso in aula','person':'persona','civil_party':'parte civile','legal_issue':'questione legale'};
const localizeContent=(text='')=>LANG==='it'?(CONTENT_IT[text]||text):text;
async function loadJson(path) { const response = await fetch(path); if (!response.ok) throw new Error(`Failed to load ${path}`); return response.json(); }
async function safeLoadJson(path, fallback) { const data=await loadJson(path); return data ?? fallback; }
const slugifyStatus = (text='') => String(text).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const normalizeStatus=(text='')=>String(text).toLowerCase().replace(/\s+/g,'_').replace(/-/g,'_');
const statusLabel=(text='')=>{ const key=`status_${normalizeStatus(text)}`; return t(key)!==key?t(key):text; };
const createBadge = (text) => `<span class="badge status-${slugifyStatus(text)}">${statusLabel(text)}</span>`;
function formatDateLabel(rawDate){ if(!rawDate) return t('date_unavailable'); const d=new Date(`${rawDate}T00:00:00Z`); return Number.isNaN(d.getTime())?rawDate:new Intl.DateTimeFormat(LANG,{month:'short',day:'2-digit',year:'numeric',timeZone:'UTC'}).format(d); }
const metricCard = (label,value,percent=0)=>`<article class="metric-card"><p class="metric-label">${label}</p><p class="metric-value">${value}</p><div class="metric-bar" style="--metric-width:${percent}%"></div></article>`;
const computeStatusShare=(c,k='verification_status')=>!c.length?0:Math.round((c.filter(i=>slugifyStatus(i[k])==='verified').length/c.length)*100);
function renderMetrics(s){ document.getElementById('metrics-grid').innerHTML=[metricCard(t('timeline_events'),s.timelineCount,100),metricCard(t('issue_streams'),s.issueCount,100),metricCard(t('hearings_tracked'),s.hearingCount,100),metricCard(t('verified_share'),`${s.verifiedShare}%`,s.verifiedShare)].join(''); }
function renderTimelineDensity(items){ const c=document.getElementById('timeline-density'); const sorted=[...items].sort((a,b)=>String(a.date).localeCompare(String(b.date))); c.innerHTML=`<div class="replay-toolbar"><div><p class="density-title">Flusso processuale</p><strong>${sorted.length} eventi ordinati nel tempo</strong></div><button id="replay-process" class="replay-button" type="button">▶ Replay del processo</button></div><div class="temporal-river">${sorted.map((i,idx)=>`<button class="river-node" data-replay-index="${idx}" style="--x:${idx};" title="${localizeContent(i.title)}"><span></span><small>${formatDateLabel(i.date)}</small></button>`).join('')}</div>`; document.getElementById('replay-process')?.addEventListener('click',()=>startReplay(sorted)); }
function startReplay(items){ clearInterval(HYDRA_REPLAY_TIMER); const nodes=[...document.querySelectorAll('.river-node')]; const cards=[...document.querySelectorAll('#timeline-list .timeline-item')]; let i=0; nodes.forEach(n=>n.classList.remove('is-current','is-past')); cards.forEach(c=>c.classList.remove('is-current','is-past')); HYDRA_REPLAY_TIMER=setInterval(()=>{ if(i>items.length){ clearInterval(HYDRA_REPLAY_TIMER); return; } nodes.forEach((n,idx)=>{n.classList.toggle('is-past',idx<i); n.classList.toggle('is-current',idx===i);}); cards.forEach((c,idx)=>{c.classList.toggle('is-past',idx<i); c.classList.toggle('is-current',idx===i);}); cards[i]?.scrollIntoView({behavior:'smooth',block:'center'}); i++; },900); }
function applyStatusFilter(filter='all'){ document.querySelectorAll('.timeline-item, .card, .network-card').forEach(card=>{const badge=card.querySelector('.badge'); if(!badge) return; card.style.display=(filter==='all'||badge.classList.contains(`status-${filter}`))?'':'none';}); document.querySelectorAll('.filter-chip').forEach(btn=>btn.classList.toggle('active',btn.dataset.filter===filter)); }
function renderStatusFilters(){ const p=document.querySelector('.context-column')||document.querySelector('.main-column'); const w=document.createElement('div'); w.className='status-filters surface'; w.innerHTML=`<p class="panel-label">${t('filter')}</p><div class="filter-row"><button class="filter-chip active" data-filter="all">${t('all')}</button><button class="filter-chip" data-filter="verified">${t('verified')}</button><button class="filter-chip" data-filter="pending-verification">${t('pending')}</button><button class="filter-chip" data-filter="partially-verified">${t('partial')}</button><button class="filter-chip" data-filter="disputed">${t('disputed')}</button><button class="filter-chip" data-filter="unverified">${t('unverified')}</button></div>`; p.querySelector('.status-filters')?.remove(); p.appendChild(w); w.querySelectorAll('.filter-chip').forEach(b=>b.onclick=()=>applyStatusFilter(b.dataset.filter)); }
function applyStaticTranslations(){ document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n; if(I18N[LANG][k]) el.textContent=I18N[LANG][k];}); }
function renderStateMessage(message){ return `<p class="state-message">${message}</p>`; }
function enableCardInteractions(){ document.querySelectorAll('#issues-grid .card, #timeline-list .timeline-item, #hearings-grid .card, #themes-strip .theme-card').forEach((card)=>{ card.tabIndex=0; card.onclick=()=>{ const alreadyActive=card.classList.contains('is-active'); document.querySelectorAll('.is-active').forEach((el)=>el.classList.remove('is-active')); if(alreadyActive){ applyIssueHighlight(''); return; } card.classList.add('is-active'); if(card.dataset.issueLabel) applyIssueHighlight(card.dataset.issueLabel||''); }; card.onkeydown=(event)=>{ if(event.key==='Enter'||event.key===' '){ event.preventDefault(); card.click(); } }; }); }
function applyIssueHighlight(issueLabel=''){ const q=issueLabel.trim().toLowerCase(); const targets=document.querySelectorAll('#timeline-list .timeline-item, #hearings-grid .card, #evidence-list .card'); if(!q){ targets.forEach((card)=>{ card.style.display=''; card.classList.remove('is-dimmed','is-match'); }); return; } targets.forEach((card)=>{ const hay=(card.dataset.search||card.textContent||'').toLowerCase(); const match=hay.includes(q); card.style.display=''; card.classList.toggle('is-dimmed',!match); card.classList.toggle('is-match',match); }); }
function renderSourceChips(sourceIds, sourceMap){ if(!sourceIds?.length) return ''; const chips=sourceIds.map((sourceId)=>{ const source=sourceMap.get(sourceId); if(!source?.url) return ''; return `<a class="source-chip" href="${source.url}" target="_blank" rel="noopener noreferrer">${source.outlet||sourceId}</a>`; }).filter(Boolean).join(''); return chips?`<p><strong>${t('related_sources')}</strong></p><div class="source-chip-row">${chips}</div>`:''; }
async function renderTimeline(data, sourceMap){ const list=document.getElementById('timeline-list'); const sorted=[...(data.items||[])].sort((a,b)=>String(a.date).localeCompare(String(b.date))); if(!sorted.length){ list.innerHTML=renderStateMessage(t('no_items')); return; } list.innerHTML=sorted.map((i,idx)=>`<article class="timeline-item" data-replay-card="${idx}" data-search="${`${localizeContent(i.title)} ${localizeContent(i.summary)}`.toLowerCase()}"><p class="eyebrow">${formatDateLabel(i.date)}</p><h3>${localizeContent(i.title)}</h3><p>${localizeContent(i.summary)}</p>${renderSourceChips(i.source_ids, sourceMap)}${createBadge(i.verification_status)}<p><strong>${t('caveat')}</strong> ${i.public_caveat}</p></article>`).join(''); }
async function renderHearings(data, sourceMap, hearingSourceMap){ const grid=document.getElementById('hearings-grid'); const hearings=data.hearings||[]; if(!hearings.length){ grid.innerHTML=renderStateMessage(t('no_items')); return; } grid.innerHTML=hearings.map(i=>`<article class="card" data-search="${`${i.public_title} ${i.summary} ${i.issue_clusters.join(' ')}`.toLowerCase()}"><p class="eyebrow">${formatDateLabel(i.date)}</p><h3>${i.public_title}</h3><p>${i.summary}</p><p><strong>${t('issue_clusters')}</strong> ${i.issue_clusters.join(', ')}</p>${renderSourceChips(hearingSourceMap.get(i.id)||[], sourceMap)}${createBadge(i.verification_status)}<p><strong>${t('caveat')}</strong> ${i.public_caveat}</p></article>`).join(''); }
function issueTone(idx){ return ['red','violet','blue','green','orange'][idx%5]; }
function renderThemeCard(i,idx){ const tone=issueTone(idx); return `<article class="theme-card theme-${tone}" data-issue-label="${i.public_label}"><strong>${i.public_label}</strong><small>${localizeContent(i.current_status)||'tema monitorato'}</small><div class="theme-spark"></div></article>`; }
async function renderIssues(data){ const grid=document.getElementById('issues-grid'); const strip=document.getElementById('themes-strip'); const issues=data.issues||[]; if(!issues.length){ grid.innerHTML=renderStateMessage(t('no_items')); if(strip) strip.innerHTML=renderStateMessage(t('no_items')); return; } if(strip) strip.innerHTML=issues.slice(0,5).map(renderThemeCard).join(''); grid.innerHTML=issues.map((i,idx)=>`<article class="card theme-detail theme-${issueTone(idx)}" data-issue-label="${i.public_label}"><h3>${i.public_label}</h3><p>${localizeContent(i.summary)}</p><p><strong>${t('status')}</strong> ${localizeContent(i.current_status)}</p><div class="trajectory-mini"><span></span><span></span><span></span><span></span></div>${createBadge(i.verification_status)}<p><strong>${t('caveat')}</strong> ${i.public_caveat}</p></article>`).join(''); }
async function renderEvidence(data){ const list=document.getElementById('evidence-list'); const caveat=document.getElementById('evidence-caveat'); if(!list) return; const items=data.items||[]; if(caveat) caveat.textContent=data.caveat||''; if(!items.length){ list.innerHTML=renderStateMessage(t('no_items')); return; } list.innerHTML=items.map((item)=>`<article class="card evidence-card" data-search="${`${item.title||''} ${item.summary||''}`.toLowerCase()}"><h3>${item.title||'Evidence'}</h3><p>${item.summary||''}</p><p><strong>Funzione</strong> fonte/documento da leggere con caveat.</p>${item.url?`<p><a href="${item.url}" target="_blank" rel="noopener noreferrer">${t('open_source')}</a></p>`:''}${createBadge(item.verification_status||'pending verification')}</article>`).join(''); }
async function renderSources(data){ const list=document.getElementById('sources-list'); const sources=data.sources||[]; if(!sources.length){ list.innerHTML=renderStateMessage(t('no_items')); return; } list.innerHTML=sources.map(i=>`<article class="source-card"><h3>${i.outlet}</h3><p><strong>${i.title}</strong></p><p>${i.public_value}</p><p><strong>${t('use_lim')}</strong> ${i.use_limitations}</p><p><a href="${i.url}" target="_blank" rel="noopener noreferrer">${t('open_source')}</a></p></article>`).join(''); }
function renderNetworkFilters(nodes, edges){ const shell=document.querySelector('#network .network-shell'); if(!shell) return {active:'all'}; const types=[...new Set(nodes.map(n=>n.type))]; const wrap=document.createElement('div'); wrap.className='network-filters'; wrap.innerHTML=`<p class="panel-label">${t('network_filters')}</p><div class="filter-row"><button class="filter-chip active" data-filter="all">${t('all')}</button>${types.map((type)=>`<button class="filter-chip" data-filter="type:${type}">${localizeContent(type)}</button>`).join('')}<button class="filter-chip" data-filter="edges">${t('only_edges')}</button></div>`; shell.parentElement?.querySelector('.network-filters')?.remove(); shell.parentElement?.insertBefore(wrap,shell); return {active:'all',wrap}; }
function applyNetworkFilter(state, nodes, edges){ const grid=document.getElementById('network-grid'); if(!grid) return; const f=state.active; const filteredNodes=f.startsWith('type:')?nodes.filter((n)=>n.type===f.slice(5)):(f==='edges'?[]:nodes); const filteredEdges=f==='edges'?edges:edges.filter((e)=>filteredNodes.some((n)=>n.id===e.source)||filteredNodes.some((n)=>n.id===e.target)); const nodeCards=filteredNodes.map(n=>`<article class="network-card"><p class="eyebrow">${t('network_nodes')} · ${localizeContent(n.type)}</p><h3>${n.public_label}</h3><p>${n.note||''}</p>${createBadge(n.quality_status||'pending verification')}</article>`).join(''); const edgeCards=filteredEdges.map(e=>{const source=nodes.find(n=>n.id===e.source)?.public_label||e.source; const target=nodes.find(n=>n.id===e.target)?.public_label||e.target; return `<article class="network-card"><p class="eyebrow">${t('network_edges')}</p><h3>${source} → ${target}</h3><p>${e.public_label}</p>${createBadge(e.quality_status||'pending verification')}</article>`;}).join(''); grid.innerHTML=nodeCards+edgeCards||renderStateMessage(t('no_items')); }
function renderNetwork(data){ const caveat=document.getElementById('network-caveat'); const grid=document.getElementById('network-grid'); if(!grid) return; const nodes=data.nodes||[]; const edges=data.edges||[]; if(caveat) caveat.textContent=data.caveat||''; renderInteractiveNetwork(nodes,edges); if(!nodes.length&&!edges.length){ grid.innerHTML=renderStateMessage(t('no_items')); return; } const state=renderNetworkFilters(nodes,edges); applyNetworkFilter(state,nodes,edges); state.wrap?.querySelectorAll('.filter-chip').forEach((btn)=>btn.addEventListener('click',()=>{ state.active=btn.dataset.filter||'all'; state.wrap?.querySelectorAll('.filter-chip').forEach((chip)=>chip.classList.toggle('active',chip===btn)); applyNetworkFilter(state,nodes,edges); })); }
function nodeColor(type){ if(type==='person') return '#2f72ff'; if(type==='civil_party') return '#22a46d'; if(type==='legal_issue') return '#f28c28'; return '#6b45df'; }
function showNetworkDetail(html){ const panel=document.getElementById('network-detail-panel'); if(panel) panel.innerHTML=html; }
function renderInteractiveNetwork(nodes,edges){ const container=document.getElementById('network-graph'); if(!container) return; if(!window.vis){ container.innerHTML='<p class="network-fallback">Network interattivo non disponibile. Visualizzazione testuale sotto.</p>'; return; } const nodeIds=new Set(nodes.map(n=>n.id)); const validEdges=edges.filter(e=>nodeIds.has(e.source)&&nodeIds.has(e.target)); const brokenEdges=edges.filter(e=>!nodeIds.has(e.source)||!nodeIds.has(e.target)); if(brokenEdges.length){ container.insertAdjacentHTML('beforebegin',`<div class="caveat-box compact">${brokenEdges.length} relazioni non renderizzate perché puntano a nodi mancanti.</div>`); } const visNodes=new window.vis.DataSet(nodes.map(n=>({id:n.id,label:n.public_label,shape:'dot',size:20,color:{background:nodeColor(n.type),border:'#ffffff'},font:{color:'#101936',size:13,strokeWidth:4,strokeColor:'#ffffff'},title:n.note||n.public_label,raw:n}))); const visEdges=new window.vis.DataSet(validEdges.map(e=>({id:e.id,from:e.source,to:e.target,label:e.public_label,color:{color:'rgba(101,112,138,.58)'},font:{color:'#46516e',size:11,strokeWidth:3,strokeColor:'#ffffff'},arrows:'to',raw:e}))); if(HYDRA_NETWORK_INSTANCE){ HYDRA_NETWORK_INSTANCE.destroy(); } HYDRA_NETWORK_INSTANCE=new window.vis.Network(container,{nodes:visNodes,edges:visEdges},{physics:{stabilization:true,barnesHut:{gravitationalConstant:-26000,springLength:150,springConstant:.04}},interaction:{hover:true,tooltipDelay:120},nodes:{borderWidth:2},edges:{smooth:{type:'dynamic'}}}); HYDRA_NETWORK_INSTANCE.on('click',(params)=>{ if(params.nodes.length){const n=nodes.find(item=>item.id===params.nodes[0]); showNetworkDetail(`<p class="eyebrow">${localizeContent(n.type)}</p><h3>${n.public_label}</h3><p>${n.note||''}</p>${createBadge(n.quality_status||'pending verification')}<p class="network-guard"><strong>${t('caveat')}</strong> ${t('anti_overclaiming')}</p>`); return;} if(params.edges.length){const e=edges.find(item=>item.id===params.edges[0]); const source=nodes.find(n=>n.id===e.source)?.public_label||e.source; const target=nodes.find(n=>n.id===e.target)?.public_label||e.target; showNetworkDetail(`<p class="eyebrow">Relazione</p><h3>${source} → ${target}</h3><p>${e.public_label}</p>${createBadge(e.quality_status||'pending verification')}<p class="network-guard"><strong>${t('caveat')}</strong> ${t('anti_overclaiming')}</p>`); return;} showNetworkDetail(`<p class="eyebrow">SELEZIONE</p><h3>${t('select_node')}</h3><p>Il dettaglio mostrerà tipologia, qualità del dato e note metodologiche.</p>`); }); }
async function init(){ applyStaticTranslations(); const loadErrors=[]; const [timeline,hearings,issues,sources,network,evidence]=await Promise.all([safeLoadJson('data/exports/public/public_timeline.json',{items:[]}).catch(()=>{loadErrors.push(t('data_timeline')); return {items:[]};}),safeLoadJson('data/exports/public/public_hearings.json',{hearings:[]}).catch(()=>{loadErrors.push(t('data_hearings')); return {hearings:[]};}),safeLoadJson('data/exports/public/public_issues.json',{issues:[]}).catch(()=>{loadErrors.push(t('data_issues')); return {issues:[]};}),safeLoadJson('data/exports/public/public_sources.json',{sources:[]}).catch(()=>{loadErrors.push(t('data_sources')); return {sources:[]};}),safeLoadJson('data/exports/public/public_network.json',{nodes:[],edges:[],caveat:''}).catch(()=>{loadErrors.push(t('data_network')); return {nodes:[],edges:[],caveat:''};}),safeLoadJson('data/exports/public/public_evidence.json',{items:[],caveat:''}).catch(()=>{loadErrors.push(t('data_evidence')); return {items:[],caveat:''};})]); const sourceMap=new Map((sources.sources||[]).map((source)=>[source.id,source])); const hearingSourceMap=new Map(); timeline.items.forEach((item)=>{ (item.linked_hearing_ids||[]).forEach((hearingId)=>{ const prev=hearingSourceMap.get(hearingId)||[]; hearingSourceMap.set(hearingId,[...new Set([...prev,...(item.source_ids||[])])]); }); }); await renderTimeline(timeline, sourceMap); renderTimelineDensity(timeline.items); await renderHearings(hearings, sourceMap, hearingSourceMap); await renderIssues(issues); await renderSources(sources); renderNetwork(network); await renderEvidence(evidence); const miss=[]; if(!hearings.hearings.length) miss.push(t('data_hearings')); if(!issues.issues.length) miss.push(t('data_issues')); if(!sources.sources.length) miss.push(t('data_sources')); if(!network.nodes.length) miss.push(t('data_network')); if(!(evidence.items||[]).length) miss.push(t('data_evidence')); const c=document.querySelector('.caveat-box'); if(c){ if(!c.dataset.baseCaveat) c.dataset.baseCaveat=c.textContent||''; c.textContent=c.dataset.baseCaveat; if(miss.length) c.insertAdjacentHTML('beforeend',` <em>${t('missing_data')}${miss.join(', ')}.</em>`); if(loadErrors.length) c.insertAdjacentHTML('beforeend',` <em>${t('error_loading')} ${loadErrors.join(', ')}.</em>`); } const verifiedShare=computeStatusShare([...timeline.items,...hearings.hearings,...issues.issues]); renderMetrics({timelineCount:timeline.items.length,issueCount:issues.issues.length,hearingCount:hearings.hearings.length,verifiedShare}); renderStatusFilters(); applyStatusFilter('all'); enableCardInteractions(); }
document.getElementById('lang-toggle')?.addEventListener('click',()=>{ LANG=LANG==='it'?'en':'it'; document.getElementById('lang-toggle').textContent=LANG==='it'?'EN':'IT'; init(); });
init();
